/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2017-07-15 01:21:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class update_002dproduct_002dform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/css/style.css", Long.valueOf(1499993241000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<title>Update Student</title>\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("<!-- This must be include to used css>\n");
      out.write("\t");
      out.write("html, body{\n");
      out.write("\tmargin-left:15px; margin-right:15px; \n");
      out.write("\tpadding:0px; \n");
      out.write("\tfont-family:Verdana, Arial, Helvetica, sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table {   \n");
      out.write("\tborder-collapse:collapse;\n");
      out.write("\tborder-bottom:1px solid gray;\n");
      out.write("\tfont-family: Tahoma,Verdana,Segoe,sans-serif;\n");
      out.write("\twidth:72%;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("th {\n");
      out.write("\tborder-bottom:1px solid gray;\n");
      out.write("\tbackground:none repeat scroll 0 0 #0775d3;\n");
      out.write("\tpadding:10px;\n");
      out.write("\tcolor: #FFFFFF;\n");
      out.write("}\n");
      out.write("\n");
      out.write("tr {\n");
      out.write("\tborder-top:1px solid \t#87CEEB;\n");
      out.write("\ttext-align:center;\t\n");
      out.write("}\n");
      out.write(" \n");
      out.write("tr:nth-child(even) {background: #FFFFFF}\n");
      out.write("tr:nth-child(odd) {background: \t#008080}\t\n");
      out.write(" \n");
      out.write("#wrapper {width: 100%; margin-top: 0px; }\n");
      out.write("#header {width: 70%; background: #0775d3; margin-top: 0px; }\n");
      out.write("#header h2 {width: 100%; margin:auto; color: #FFFFFF;}\n");
      out.write("#container {width: 100%; margin:auto}\n");
      out.write("#container h3 {color: #000;}\n");
      out.write("#container #content {margin-top: 20px;}\n");
      out.write("\n");
      out.write(".add-student-button {\n");
      out.write("\tborder: 1px solid #666; \n");
      out.write("\tborder-radius: 5px; \n");
      out.write("\tpadding: 4px; \n");
      out.write("\tfont-size: 12px;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\twidth: 120px; \n");
      out.write("\tpadding: 5px 10px; \n");
      out.write("\t\n");
      out.write("\tmargin-bottom: 15px;\n");
      out.write("\tbackground: #cccccc;\n");
      out.write("}");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div id =\"wrapper\">\n");
      out.write("\t\t<div id =\"header\">\n");
      out.write("\t\t\t<h2>Update product page</h2>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div id=\"container\">\n");
      out.write("\t\t<h3>Update Product</h3>\n");
      out.write("\t\t<form action=\"productControllerServlet\" method=\"GET\">\n");
      out.write("\t\t\t<input type =\"hidden\" name =\"command\" value =\"UPDATE\"/>\n");
      out.write("\t\t\t<input type =\"hidden\" name =\"productId\" value =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${THE_PRODUCT.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("\t\t\t<table>\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- <!-- id,sku,pic,name,pict,price,delieverFee,descript,seller,categ,postDate   -->\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><label>sku:</label></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"_Sku\" \n");
      out.write("\t\t\t\t\t\t\tvalue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${THE_PRODUCT.sku}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><label>pic:</label></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"_Pictureurl\" \n");
      out.write("\t\t\t\t\t\t\tvalue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${THE_PRODUCT.picurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><label>name:</label></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"_Name\" \n");
      out.write("\t\t\t\t\t\t\tvalue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${THE_PRODUCT.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><label>pict:</label></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"_Pict\" \n");
      out.write("\t\t\t\t\t\t\tvalue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${THE_PRODUCT.pict}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><label>price:</label></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"_Price\" \n");
      out.write("\t\t\t\t\t\t\tvalue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${THE_PRODUCT.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><label>delieverFee:</label></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"_DelieverFee\" \n");
      out.write("\t\t\t\t\t\t\tvalue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${THE_PRODUCT.delieverFee}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><label>descript:</label></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"_Descript\" \n");
      out.write("\t\t\t\t\t\t\tvalue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${THE_PRODUCT.descript}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><label>seller:</label></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"_Seller\" \n");
      out.write("\t\t\t\t\t\t\tvalue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${THE_PRODUCT.seller}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><label>categ:</label></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"_Categ\" \n");
      out.write("\t\t\t\t\t\t\tvalue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${THE_PRODUCT.categ}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td><label></label></td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" value=\"Save\" class=\"save\"/></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</tbody>\t\n");
      out.write("\t\t\t</table>\n");
      out.write("\n");
      out.write("\t\t</form>\n");
      out.write("\t\t\n");
      out.write("\t\t<div type=\"clear:\" both;\"></div>\n");
      out.write("\t\t\n");
      out.write("\t\t<p>\n");
      out.write("\t\t\t<a href=\"productControllerServlet\">Back to List</a>\n");
      out.write("\t\t\n");
      out.write("\t\t</p>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
